using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// The participant-facing launch menu: a passthrough-MR panel floating in the participant's
/// real room, on which they pick which task this run uses and hit START to enter MR_Scene.
///
/// WHY THIS EXISTS: Risk Level is a WITHIN-subjects factor, so each participant runs 2-4
/// tasks. Without a menu, every task means a fresh Android build with the participant sitting
/// in the headset. The task is the only per-run variable — participant id and the visual
/// conditions are set once by the researcher on STUDY SETUP in this scene before the build — so a
/// menu that changes ONLY the task removes every mid-session rebuild.
///
/// WHAT THE PARTICIPANT SEES AND DOES NOT SEE:
///  - SEES: their participant id (read-only, so the researcher can verify the right build is
///    on the headset without touching it), and eight buttons labelled "任務 A".."任務 H".
///  - DOES NOT SEE: the condition (Scale / Render Style). Displaying it would tell the
///    participant what the study manipulates and blow the whole design.
///  - DOES NOT SEE: task NAMES. The buttons are bare letters on purpose — "Office Chairs" vs
///    "Strategic Partnership" would preview the scenario before the SWOT panel does, and make
///    it obvious that A-D are the small-money tasks and E-H the large ones. That IS the Risk
///    manipulation, so it must stay unlabelled. The researcher tells the participant aloud
///    which letter to press.
///
/// WHY IT DOES NOT USE THE EventSystem / OVRInputModule / OVRRaycaster STACK: that path needs
/// an EventSystem, a raycaster on the canvas, a ray transform and a cursor all wired together,
/// and it silently does nothing if any one of them is wrong. This is a participant-facing
/// critical path where a dead menu ends the session, so the ray is cast and hit-tested here
/// directly against the button rects — one ray drives the drawn laser, the cursor dot, the
/// hover tint and the click, so what is highlighted is always exactly what will be pressed.
///
/// WHY THE RAY IS DRAWN: the controller models are hidden in this study, so with only a cursor
/// dot there is nothing linking the participant's hand to the panel — and nothing at all on
/// screen until their aim happens to cross it. Pointing becomes trial and error at the exact
/// moment the participant is least oriented. The laser makes aim continuously visible.
///
/// SETUP: generated by Tools > Study > Create or Refresh Launch Scene. The UI is built at
/// runtime (same approach as SwotPanel), so there is no prefab hierarchy to wire or to drift.
/// </summary>
[DisallowMultipleComponent]
public class LaunchMenu : MonoBehaviour
{
    [Header("Settings source")]
    [Tooltip("The STUDY SETUP object in this scene, which the researcher edits per participant. " +
             "Only the participant id is read, for display. The conditions travel to MR_Scene via " +
             "StudySession and are never shown here. Auto-found in the scene if left empty.")]
    public StudySetup setup;

    [Tooltip("PRACTICE BUILD ONLY — must stay OFF in Launch_Scene. When ON, the header reads " +
             "練習模式 instead of a participant id, and no StudySetup is required. The practice " +
             "APK is built once and reused across participants, so a baked-in id would be " +
             "somebody else's. Set automatically by Tools > Study > Create or Refresh Demo Scene.")]
    public bool demoMode = false;

    [Header("Scene to load")]
    [Tooltip("Name of the scene to load when START is pressed. Must be in Build Settings. " +
             "MR_Scene for the study; DemoScene for the practice build.")]
    public string studySceneName = "MR_Scene";

    [Header("Text")]
    [Tooltip("Instruction line shown above the task buttons. The researcher tells the participant " +
             "which letter to press; this is only the prompt.")]
    [TextArea]
    public string instruction = "請選擇研究人員告知你的任務，然後按下「開始」。";

    [Tooltip("REQUIRED: a TMP font asset with Traditional Chinese (CJK) coverage — the study " +
             "build uses 'Assets/Fonts/msjh SDF', the same asset SwotPanel uses. The project's " +
             "default TMP font (LiberationSans) has NO CJK glyphs, so leaving this empty renders " +
             "every Chinese character as a blank box. NOTE that asset is a STATIC atlas: any " +
             "character not baked into it will not render and will not fall back, so if you " +
             "reword the text here, verify the new characters actually appear on the headset.")]
    public TMP_FontAsset fontOverride;

    [Header("Placement")]
    [Tooltip("Distance in front of the participant's head, in meters, where the panel is placed.")]
    public float viewDistance = 1.15f;

    [Tooltip("Vertical shift relative to eye height, in meters (negative = below eye level, a " +
             "natural slightly-downward reading angle).")]
    public float heightOffset = -0.12f;

    [Tooltip("Physical width of the panel in meters. Height follows the reference aspect.")]
    public float panelWidthMeters = 0.85f;

    [Tooltip("Seconds to wait before placing the panel. Head tracking is not valid on the very " +
             "first frames, so placing immediately can strand the panel at the world origin.")]
    public float placeDelaySeconds = 0.4f;

    [Header("Input")]
    [Tooltip("Also accept keyboard 1-8 to select and Return to start. For editor testing only — " +
             "harmless on the headset, which has no keyboard.")]
    public bool enableKeyboardFallback = true;

    [Header("Pointer ray")]
    [Tooltip("Draw a visible laser from the controller to whatever it is aimed at. The controller " +
             "MODELS are hidden in this study (deliberately), so without this the participant has " +
             "no indication of where they are pointing until the ray happens to land on the panel.")]
    public bool showPointerRay = true;

    [Tooltip("How far the ray is drawn, in meters, when it is NOT pointing at the panel. This is " +
             "the case that matters: it is what lets the participant see their aim and sweep it " +
             "onto the menu. When it does hit, the ray stops at the panel instead.")]
    public float rayMaxLength = 2.5f;

    [Tooltip("Thickness of the ray at the controller end, in meters. It tapers toward the far end " +
             "so the aim reads as a direction rather than a bar.")]
    public float rayWidth = 0.006f;

    [Header("Debug")]
    [Tooltip("Logs placement, hover and selection so a dead menu can be diagnosed from adb logcat.")]
    public bool verboseLogging = true;

    // ---- Reference canvas resolution (pixels). Width maps to panelWidthMeters. ----
    private const float RefWidth = 1400f;
    private const float RefHeight = 900f;

    // ---- Button colours ----
    private static readonly Color BtnIdle     = new Color(1f, 1f, 1f, 0.10f);
    private static readonly Color BtnHover    = new Color(1f, 1f, 1f, 0.24f);
    private static readonly Color BtnSelected = new Color(0.35f, 0.65f, 1f, 0.85f);
    private static readonly Color StartReady  = new Color(0.30f, 0.75f, 0.45f, 0.90f);
    private static readonly Color StartHover  = new Color(0.38f, 0.88f, 0.55f, 1.00f);
    private static readonly Color StartOff    = new Color(1f, 1f, 1f, 0.07f);

    // ---- Pointer ray colours ----
    // The ray brightens on hover, so "this press will land on a button" is legible from the ray
    // itself, not only from the button tint the participant may not be looking directly at.
    private static readonly Color RayIdle  = new Color(1f, 1f, 1f, 0.35f);
    private static readonly Color RayHover = new Color(0.55f, 0.80f, 1f, 0.95f);

    // Distance from the hand anchor at which the ray starts drawing, in meters. The anchor sits
    // inside the fist, so a ray drawn from it appears to sprout out of the participant's hand.
    private const float RayStartOffset = 0.03f;

    // The ray stops this far short of the panel so its tip does not z-fight the panel surface.
    // The cursor dot marks the exact point; the ray only has to get the eye there.
    private const float RayTipGap = 0.012f;

    private class MenuButton
    {
        public RectTransform rect;
        public Image bg;
        public TextMeshProUGUI label;
        public bool isStart;
        public StudyControlPanel.StudyTask task;
    }

    private readonly List<MenuButton> buttons = new List<MenuButton>();
    private MenuButton startButton;

    private GameObject canvasGO;
    private RectTransform canvasRect;
    private RectTransform cursorRect;
    private TextMeshProUGUI selectedText;

    private OVRCameraRig rig;
    private Transform cameraTransform;

    // ---- Aim state, written by UpdateAimAndHover and read by UpdateRayVisual, so the drawn ray
    // is the SAME ray that did the hit-testing rather than a second one that could disagree. ----
    private readonly List<Transform> aimSources = new List<Transform>(2);   // reused: no per-frame alloc
    private Transform aimSource;        // the source the cursor/hover currently belongs to
    private bool aimFromController;     // false = gaze fallback, which draws no ray (see UpdateRayVisual)
    private bool aimHasHit;
    private Vector3 aimHitPoint;

    private GameObject rayGO;
    private LineRenderer rayLine;
    private Material rayMaterial;       // created at runtime; destroyed in OnDestroy

    private bool placed;
    private bool hasSelection;
    private StudyControlPanel.StudyTask selectedTask;
    private bool starting;   // guards against a double-press loading the scene twice

    private void Start()
    {
        if (setup == null) setup = FindObjectOfType<StudySetup>();

        if (setup == null && !demoMode)
            Debug.LogWarning("LaunchMenu: no StudySetup in the scene — the participant id will " +
                             "show as unset, and MR_Scene will fall back to STUDY CONTROL's own " +
                             "inspector values instead of this participant's conditions.");

        Build();
    }

    // =========================================================================
    //  Placement
    // =========================================================================

    private void ResolveCamera()
    {
        if (cameraTransform != null) return;

        // On Quest the OVR center-eye camera is often NOT tagged MainCamera, so Camera.main
        // can be null — fall back to the rig, then to any camera, so placement never silently
        // fails and strands the panel at the world origin.
        if (rig == null) rig = FindObjectOfType<OVRCameraRig>();
        if (rig != null && rig.centerEyeAnchor != null) { cameraTransform = rig.centerEyeAnchor; return; }
        if (Camera.main != null) { cameraTransform = Camera.main.transform; return; }
        var anyCam = FindObjectOfType<Camera>();
        if (anyCam != null) cameraTransform = anyCam.transform;
    }

    /// <summary>
    /// World-lock the panel in front of the participant. World-locked rather than head-following
    /// so they can look straight at it and aim at a button without it sliding away with their gaze.
    /// Re-centred on demand with B/Y, since a participant may be seated facing a different way
    /// than when the app started.
    /// </summary>
    private void PlaceInFrontOfHead()
    {
        ResolveCamera();
        if (cameraTransform == null) return;

        Vector3 eye = cameraTransform.position;
        Vector3 fwd = cameraTransform.forward;
        fwd.y = 0f;                                     // yaw only -> level, stable height
        if (fwd.sqrMagnitude < 1e-4f) fwd = Vector3.forward;
        fwd.Normalize();

        canvasRect.position = eye + fwd * viewDistance + Vector3.up * heightOffset;
        // Canvas front faces the participant when its forward points AWAY from them.
        canvasRect.rotation = Quaternion.LookRotation(canvasRect.position - eye, Vector3.up);
        canvasGO.SetActive(true);
        placed = true;

        Log($"placed at {canvasRect.position} (eye={eye}).");
    }

    // =========================================================================
    //  Per-frame: place, aim, hover, click
    // =========================================================================

    private void Update()
    {
        if (canvasRect == null) return;

        if (!placed)
        {
            // Head pose is not valid on the first frames; placing then puts the panel at origin.
            if (Time.timeSinceLevelLoad < placeDelaySeconds) return;
            PlaceInFrontOfHead();
            return;
        }

        // Re-centre (B on the right controller / Y on the left) if the participant has turned away.
        if (OVRInput.GetDown(OVRInput.Button.Two)) PlaceInFrontOfHead();

        MenuButton hovered = UpdateAimAndHover();
        UpdateRayVisual(hovered);

        bool clicked = OVRInput.GetDown(OVRInput.Button.PrimaryIndexTrigger, OVRInput.Controller.RTouch)
                    || OVRInput.GetDown(OVRInput.Button.PrimaryIndexTrigger, OVRInput.Controller.LTouch)
                    || OVRInput.GetDown(OVRInput.Button.One);   // A / X, for participants who miss the trigger

        if (clicked && hovered != null) Press(hovered);

        if (enableKeyboardFallback) KeyboardFallback();
    }

    /// <summary>
    /// Cast from each controller at the canvas plane, find which button (if any) the ray lands
    /// on, park the cursor dot at the hit point, and tint the buttons accordingly. Returns the
    /// hovered button so the click handler acts on exactly what the participant can see is lit.
    /// </summary>
    private MenuButton UpdateAimAndHover()
    {
        if (rig == null) rig = FindObjectOfType<OVRCameraRig>();

        MenuButton hovered = null;
        bool haveHit = false;
        Vector3 hitPoint = Vector3.zero;

        CollectAimSources();

        // Default the drawn ray to the first (preferred) source, so a participant pointing well
        // away from the panel still sees where they are aiming — that is the whole reason the ray
        // exists, and it is exactly the case where nothing is hit.
        aimSource = aimSources.Count > 0 ? aimSources[0] : null;

        // The canvas front faces the participant, so the plane normal is -forward.
        var plane = new Plane(-canvasRect.forward, canvasRect.position);

        foreach (var src in aimSources)
        {
            var ray = new Ray(src.position, src.forward);
            if (!plane.Raycast(ray, out float enter)) continue;

            Vector3 p = ray.GetPoint(enter);
            // Show the cursor even off the buttons, and attribute it to the source that produced
            // it, so the ray and the dot can never come from different hands.
            if (!haveHit) { haveHit = true; hitPoint = p; aimSource = src; }

            MenuButton b = ButtonAt(p);
            if (b != null) { hovered = b; hitPoint = p; aimSource = src; break; }
        }

        aimHasHit = haveHit;
        aimHitPoint = hitPoint;

        // Cursor dot: nudged toward the participant so it never z-fights the panel behind it.
        if (cursorRect != null)
        {
            cursorRect.gameObject.SetActive(haveHit);
            if (haveHit) cursorRect.position = hitPoint - canvasRect.forward * 0.002f;
        }

        Repaint(hovered);
        return hovered;
    }

    /// <summary>
    /// Rebuild the list of transforms to cast from, right hand first so a right-handed
    /// participant's ray wins when both point at the panel.
    ///
    /// Only CONNECTED controllers are included. A hand anchor keeps its last pose after its
    /// controller sleeps or dies, so casting from a disconnected one would let a stale pose steal
    /// the hover — and, now that the ray is drawn, paint a laser out of a controller lying on the
    /// table.
    ///
    /// The head ray is a LAST RESORT, used only when no controller is connected at all so the menu
    /// is still operable by looking at a button. It must NOT sit alongside the controller rays:
    /// with both live, a controller aimed off-panel would hand control to gaze, the cursor would
    /// jump between hand-aim and gaze-aim, and a participant could select a button they were not
    /// pointing at.
    /// </summary>
    private void CollectAimSources()
    {
        aimSources.Clear();

        if (rig != null)
        {
            if (OVRInput.IsControllerConnected(OVRInput.Controller.RTouch) && rig.rightHandAnchor != null)
                aimSources.Add(rig.rightHandAnchor);
            if (OVRInput.IsControllerConnected(OVRInput.Controller.LTouch) && rig.leftHandAnchor != null)
                aimSources.Add(rig.leftHandAnchor);
        }

        aimFromController = aimSources.Count > 0;
        if (aimFromController) return;

        ResolveCamera();
        if (cameraTransform != null) aimSources.Add(cameraTransform);
    }

    /// <summary>
    /// Draw the aim ray from the controller to whatever it is pointing at.
    ///
    /// WHY THIS IS NOT COSMETIC: the controller models are hidden in this study, so before the ray
    /// lands on the panel there is nothing on screen connecting the participant's hand to the
    /// cursor — pointing becomes guesswork until the dot happens to appear.
    ///
    /// NOT drawn for the gaze fallback: a line starting at the eye is a dot at the centre of view
    /// that smears across the panel as the head turns. The cursor already shows gaze aim.
    /// </summary>
    private void UpdateRayVisual(MenuButton hovered)
    {
        if (rayLine == null) return;

        bool show = showPointerRay && aimFromController && aimSource != null;
        if (rayGO.activeSelf != show) rayGO.SetActive(show);
        if (!show) return;

        Vector3 dir = aimSource.forward;
        Vector3 origin = aimSource.position + dir * RayStartOffset;
        Vector3 end = aimHasHit ? aimHitPoint - dir * RayTipGap
                                : origin + dir * rayMaxLength;

        // If the panel is closer than the start offset + tip gap the subtraction above would put
        // the end BEHIND the origin and flip the ray back through the participant's hand.
        if (Vector3.Dot(end - origin, dir) <= 0f) end = origin + dir * 0.01f;

        rayLine.SetPosition(0, origin);
        rayLine.SetPosition(1, end);

        Color c = hovered != null ? RayHover : RayIdle;
        rayLine.startColor = c;
        rayLine.endColor = new Color(c.r, c.g, c.b, c.a * 0.35f);   // fades out toward the tip
    }

    /// <summary>Which button contains this world point, if any.</summary>
    private MenuButton ButtonAt(Vector3 worldPoint)
    {
        foreach (var b in buttons)
        {
            if (b.isStart && !hasSelection) continue;    // START is inert until a task is picked
            Vector3 local = b.rect.InverseTransformPoint(worldPoint);
            if (b.rect.rect.Contains(local)) return b;
        }
        return null;
    }

    /// <summary>Tint every button for the current hover + selection state.</summary>
    private void Repaint(MenuButton hovered)
    {
        foreach (var b in buttons)
        {
            if (b.isStart)
            {
                b.bg.color = !hasSelection ? StartOff : (b == hovered ? StartHover : StartReady);
                continue;
            }

            bool isSelected = hasSelection && b.task == selectedTask;
            b.bg.color = isSelected ? BtnSelected : (b == hovered ? BtnHover : BtnIdle);
        }
    }

    private void Press(MenuButton b)
    {
        if (b.isStart) { StartStudy(); return; }

        hasSelection = true;
        selectedTask = b.task;
        selectedText.text = $"已選擇：{Letter(b.task)}";
        Log($"task selected = {b.task}.");
    }

    private void KeyboardFallback()
    {
        var tasks = (StudyControlPanel.StudyTask[])System.Enum.GetValues(typeof(StudyControlPanel.StudyTask));
        for (int i = 0; i < tasks.Length && i < 9; i++)
        {
            if (!Input.GetKeyDown(KeyCode.Alpha1 + i)) continue;
            hasSelection = true;
            selectedTask = tasks[i];
            selectedText.text = $"已選擇：{Letter(tasks[i])}";
            Log($"task selected via keyboard = {tasks[i]}.");
        }

        if (Input.GetKeyDown(KeyCode.Return) && hasSelection) StartStudy();
    }

    /// <summary>
    /// Hand the choice to <see cref="StudySession"/> and load the study scene. The task is
    /// deliberately NOT written back onto STUDY SETUP: that object is the researcher's pre-build
    /// configuration and a runtime write would not persist in a build anyway.
    /// </summary>
    private void StartStudy()
    {
        if (starting) return;   // a double trigger-pull must not load the scene twice
        if (!hasSelection) return;
        starting = true;

        StudySession.SetTask(selectedTask);
        // The RAW id here, not the localized header line — this goes to adb logcat and the
        // console mirror, where it needs to match the id in the log file name.
        string pid = setup != null ? setup.config.participantId : (demoMode ? "practice" : "unset");
        Debug.Log($"LaunchMenu: starting — participant='{pid}', task={selectedTask} " +
                  $"('{StudyControlPanel.ToTaskKey(selectedTask)}'). Loading '{studySceneName}'.");

        SceneManager.LoadScene(studySceneName);
    }

    /// <summary>
    /// The header line. In the practice build it is deliberately a fixed word rather than an id:
    /// that APK is built once and sideloaded to every headset, so any id compiled into it would
    /// belong to whoever happened to be the participant on build day.
    ///
    /// The participant id itself stays Latin (P01, …) — it is an identifier the researcher reads
    /// back, not prose, and transliterating it would make the two disagree.
    /// </summary>
    private string HeaderLine =>
        demoMode ? "練習模式"
                 : "受試者ID：" + (setup != null ? setup.config.participantId : "未設定");

    /// <summary>Shown when no task has been picked yet.</summary>
    private const string NothingSelected = "尚未選擇";

    /// <summary>
    /// "任務 A" .. "任務 H" — the letter only, never the scenario name (see class header).
    /// The LETTER stays Latin so it matches exactly what the researcher says aloud and what the
    /// task keys / log files use; only the word around it is localized.
    /// </summary>
    private static string Letter(StudyControlPanel.StudyTask t)
    {
        string s = t.ToString();                  // e.g. "C_CoffeeMachine"
        int underscore = s.IndexOf('_');
        return "任務 " + (underscore > 0 ? s.Substring(0, underscore) : s);
    }

    /// <summary>ASCII name for the runtime hierarchy, so debugging stays readable.</summary>
    private static string AsciiName(StudyControlPanel.StudyTask t)
    {
        string s = t.ToString();
        int underscore = s.IndexOf('_');
        return "Task" + (underscore > 0 ? s.Substring(0, underscore) : s);
    }

    private void Log(string msg)
    {
        if (verboseLogging) Debug.Log("LaunchMenu: " + msg);
    }

    // =========================================================================
    //  UI construction (runtime, so there is no prefab hierarchy to wire or drift)
    // =========================================================================

    private void Build()
    {
        canvasGO = new GameObject("LaunchMenu_Canvas");
        var canvas = canvasGO.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.WorldSpace;
        canvasGO.AddComponent<CanvasScaler>();

        canvasRect = canvasGO.GetComponent<RectTransform>();
        canvasRect.sizeDelta = new Vector2(RefWidth, RefHeight);
        canvasRect.localScale = Vector3.one * (panelWidthMeters / RefWidth);

        // Background
        MakePanel(canvasRect, Vector2.zero, Vector2.one, new Color(0.07f, 0.09f, 0.13f, 0.94f));

        // Participant id — shown so the researcher can confirm the right build is on the headset
        // without taking it off. Read-only: there is no edit affordance anywhere on this menu.
        var pid = MakeText(canvasRect, "ParticipantId", new Vector2(0.04f, 0.87f), new Vector2(0.96f, 0.97f),
            40f, new Color(0.62f, 0.70f, 0.82f), TextAlignmentOptions.Left);
        pid.text = HeaderLine;

        var instr = MakeText(canvasRect, "Instruction", new Vector2(0.04f, 0.72f), new Vector2(0.96f, 0.86f),
            34f, Color.white, TextAlignmentOptions.TopLeft);
        instr.text = instruction;

        // 4x2 grid of task buttons.
        var grid = MakePanel(canvasRect, new Vector2(0.04f, 0.30f), new Vector2(0.96f, 0.70f),
            new Color(0, 0, 0, 0));   // transparent container
        BuildTaskGrid(grid.rectTransform);

        selectedText = MakeText(canvasRect, "Selected", new Vector2(0.04f, 0.20f), new Vector2(0.96f, 0.29f),
            32f, new Color(0.55f, 0.78f, 1f), TextAlignmentOptions.Center);
        selectedText.text = NothingSelected;

        startButton = MakeButton(canvasRect, "Start", "開始",
            new Vector2(0.33f, 0.04f), new Vector2(0.67f, 0.18f), 44f);
        startButton.isStart = true;

        // Cursor LAST so it draws on top of everything (UI sorts by hierarchy order, not depth).
        var cursor = MakePanel(canvasRect, new Vector2(0.5f, 0.5f), new Vector2(0.5f, 0.5f), new Color(1f, 1f, 1f, 0.95f));
        cursorRect = cursor.rectTransform;
        cursorRect.sizeDelta = new Vector2(16f, 16f);
        cursorRect.gameObject.name = "Cursor";
        cursorRect.gameObject.SetActive(false);

        Repaint(null);

        BuildPointerRay();

        // Hidden until placed: head tracking is invalid for the first frames, so an immediately
        // visible panel would flash at the world origin before jumping in front of the participant.
        canvasGO.SetActive(false);
    }

    /// <summary>
    /// Build the aim ray. It is a ROOT object, not a child of the canvas: the canvas is scaled to
    /// about 1/1600 to map its reference pixels onto meters, and a LineRenderer parented under
    /// that would inherit the scale and vanish.
    ///
    /// SHADER CHOICE: "Sprites/Default" is in this project's Always Included Shaders, so it
    /// survives the Android build. That is not incidental — see SceneDepthOccluder, where a
    /// Shader.Find on a shader NOTHING referenced from an asset was silently stripped from the
    /// build and the feature only failed on device. If the lookup fails here, say so loudly and
    /// drop the ray rather than shipping a magenta laser at a participant.
    /// </summary>
    private void BuildPointerRay()
    {
        var shader = Shader.Find("Sprites/Default");
        if (shader == null)
        {
            Debug.LogError("LaunchMenu: shader 'Sprites/Default' not found — pointer ray disabled. " +
                           "Add it to Project Settings > Graphics > Always Included Shaders.");
            showPointerRay = false;
            return;
        }

        rayGO = new GameObject("LaunchMenu_PointerRay");
        rayLine = rayGO.AddComponent<LineRenderer>();

        rayMaterial = new Material(shader);
        rayLine.material = rayMaterial;

        rayLine.useWorldSpace = true;
        rayLine.positionCount = 2;
        rayLine.numCapVertices = 4;      // rounded ends; a hard rectangle reads as a plank
        rayLine.startWidth = rayWidth;
        rayLine.endWidth = rayWidth * 0.35f;
        rayLine.startColor = RayIdle;
        rayLine.endColor = RayIdle;
        rayLine.textureMode = LineTextureMode.Stretch;
        rayLine.alignment = LineAlignment.View;   // always faces the participant, so it never
                                                  // thins to an invisible edge at some angles

        // Nothing about a UI laser wants to interact with lighting.
        rayLine.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        rayLine.receiveShadows = false;
        rayLine.lightProbeUsage = UnityEngine.Rendering.LightProbeUsage.Off;
        rayLine.reflectionProbeUsage = UnityEngine.Rendering.ReflectionProbeUsage.Off;

        rayGO.SetActive(false);
    }

    /// <summary>
    /// The ray material is created with `new Material(...)`, so it is not owned by any asset and
    /// Unity will not collect it — leaking one per play-mode entry in the Editor.
    /// </summary>
    private void OnDestroy()
    {
        if (rayMaterial == null) return;
        if (Application.isPlaying) Destroy(rayMaterial);
        else DestroyImmediate(rayMaterial);
    }

    private void BuildTaskGrid(RectTransform parent)
    {
        var tasks = (StudyControlPanel.StudyTask[])System.Enum.GetValues(typeof(StudyControlPanel.StudyTask));
        const int cols = 4;
        int rows = Mathf.CeilToInt(tasks.Length / (float)cols);

        const float gapX = 0.02f, gapY = 0.06f;
        float cellW = 1f / cols, cellH = 1f / rows;

        for (int i = 0; i < tasks.Length; i++)
        {
            int col = i % cols;
            int row = i / cols;
            // Row 0 must be the TOP row; anchor Y runs bottom-up, so invert.
            float yMax = 1f - row * cellH;

            var b = MakeButton(parent, AsciiName(tasks[i]), Letter(tasks[i]),
                new Vector2(col * cellW + gapX, yMax - cellH + gapY),
                new Vector2((col + 1) * cellW - gapX, yMax - gapY),
                40f);
            b.task = tasks[i];
        }
    }

    /// <summary>
    /// <paramref name="name"/> stays ASCII so the runtime hierarchy is readable while debugging;
    /// <paramref name="text"/> is the localized label the participant actually reads. Same split
    /// SwotPanel.BuildQuadrant uses.
    /// </summary>
    private MenuButton MakeButton(RectTransform parent, string name, string text,
        Vector2 aMin, Vector2 aMax, float fontSize)
    {
        var go = new GameObject("Btn_" + name, typeof(RectTransform));
        var rt = go.GetComponent<RectTransform>();
        rt.SetParent(parent, false);
        rt.anchorMin = aMin;
        rt.anchorMax = aMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;

        var img = go.AddComponent<Image>();
        img.color = BtnIdle;
        img.raycastTarget = false;   // hit-testing is done by this script, not the EventSystem

        var label = MakeText(rt, "Label", Vector2.zero, Vector2.one, fontSize, Color.white,
            TextAlignmentOptions.Center);
        label.text = text;

        var b = new MenuButton { rect = rt, bg = img, label = label };
        buttons.Add(b);
        return b;
    }

    private Image MakePanel(RectTransform parent, Vector2 aMin, Vector2 aMax, Color color)
    {
        var go = new GameObject("Panel", typeof(RectTransform));
        var rt = go.GetComponent<RectTransform>();
        rt.SetParent(parent, false);
        rt.anchorMin = aMin;
        rt.anchorMax = aMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        var img = go.AddComponent<Image>();
        img.color = color;
        img.raycastTarget = false;
        return img;
    }

    private TextMeshProUGUI MakeText(RectTransform parent, string name, Vector2 aMin, Vector2 aMax,
        float fontSize, Color color, TextAlignmentOptions align)
    {
        const float pad = 10f;
        var go = new GameObject(name, typeof(RectTransform));
        var rt = go.GetComponent<RectTransform>();
        rt.SetParent(parent, false);
        rt.anchorMin = aMin;
        rt.anchorMax = aMax;
        rt.offsetMin = new Vector2(pad, pad);
        rt.offsetMax = new Vector2(-pad, -pad);

        var tmp = go.AddComponent<TextMeshProUGUI>();
        if (fontOverride != null) tmp.font = fontOverride;
        tmp.fontSize = fontSize;
        tmp.color = color;
        tmp.alignment = align;
        tmp.enableWordWrapping = true;
        tmp.overflowMode = TextOverflowModes.Overflow;
        tmp.raycastTarget = false;
        return tmp;
    }
}
